// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM7JUvXfn73LMmTqQ78iZE0YL8HWmKwok',
    appId: '1:368009015322:android:d2180019ac6964efdea1a3',
    messagingSenderId: '368009015322',
    projectId: 'order-tracking-app-b5b92',
    storageBucket: 'order-tracking-app-b5b92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0qpapVOXu5j1HK-2d2Z-Kl37NeLCKqjU',
    appId: '1:368009015322:ios:2afe0ddbc89fc08adea1a3',
    messagingSenderId: '368009015322',
    projectId: 'order-tracking-app-b5b92',
    storageBucket: 'order-tracking-app-b5b92.firebasestorage.app',
    iosClientId: '368009015322-atvpnin0vopn6vd0mt47tou94n0natng.apps.googleusercontent.com',
    iosBundleId: 'com.example.orderTrackingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0qpapVOXu5j1HK-2d2Z-Kl37NeLCKqjU',
    appId: '1:368009015322:ios:2afe0ddbc89fc08adea1a3',
    messagingSenderId: '368009015322',
    projectId: 'order-tracking-app-b5b92',
    storageBucket: 'order-tracking-app-b5b92.firebasestorage.app',
    iosClientId: '368009015322-atvpnin0vopn6vd0mt47tou94n0natng.apps.googleusercontent.com',
    iosBundleId: 'com.example.orderTrackingApp',
  );
}
